version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app.py:/app/app.py
    restart: unless-stopped

  # Frontend (optional, if you want to use the provided HTML frontend)
  # Use a simple HTTP server to serve the frontend
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped